package au.gov.ga.worldwind.viewer.layers.tiled.image.delegate;

public interface Delegate
{
	/**
	 * Generate a new Delegate from a string definition. Must return
	 * {@code null} if the provided definition string could not possibly be
	 * generated by the {@code toDefinition()} function.
	 * 
	 * @param definition
	 * @return New delegate if the definition is valid for this delegate
	 */
	Delegate fromDefinition(String definition);

	/**
	 * Generate a definition string for this delegate. Must be a string accepted
	 * by the {@code fromDefinition()} function.
	 * 
	 * @return
	 */
	String toDefinition();
}
