package au.gov.ga.worldwind.common.layers.tiled.image.delegate;

import gov.nasa.worldwind.geom.Sector;
import gov.nasa.worldwind.layers.TextureTile;
import gov.nasa.worldwind.util.Level;
import gov.nasa.worldwind.util.TileKey;

/**
 * Instances of {@link TileFactoryDelegate} are used when creating new
 * TextureTiles, and also for transforming the {@link TileKey}s when
 * loading/saving TextureTiles from/to the texture memory cache.
 * 
 * @author Michael de Hoog
 */
public interface TileFactoryDelegate extends Delegate
{
	/**
	 * Create a new {@link TextureTile} with the given parameters.
	 * 
	 * @param sector
	 * @param level
	 * @param row
	 * @param col
	 * @return New {@link TextureTile}
	 */
	TextureTile createTextureTile(Sector sector, Level level, int row, int col);

	/**
	 * Transform a {@link TileKey}. This is useful when multiple layers have the
	 * same data cache name and therefore similar tiles will have duplicate
	 * {@link TileKey}s. Transforming the {@link TileKey} will ensure that they
	 * are different.
	 * 
	 * It would be nicer for the {@link TextureTile}s generated by the
	 * createTextureTile() function to override the getTileKey() function, but
	 * unfortunately it is a final method.
	 * 
	 * @param tileKey
	 * @return Transformed {@link TileKey}
	 */
	TileKey transformTileKey(TileKey tileKey);
}
