package au.gov.ga.worldwind.common.layers.delegate;

import gov.nasa.worldwind.avlist.AVList;

import org.w3c.dom.Element;

import au.gov.ga.worldwind.common.layers.tiled.image.delegate.DelegatorTiledImageLayer;

/**
 * Super-interface which all delegates implement. Defines functions which allow
 * saving delegates to a string definition and loading a new instance from a
 * string definition.
 * 
 * @author Michael de Hoog
 */
public interface IDelegate
{
	/**
	 * Generate a new Delegate from a string definition. Must return
	 * {@code null} if the provided definition string could not possibly be
	 * generated by the {@code toDefinition()} function.
	 * 
	 * @param definition
	 *            Definition string
	 * @param layerElement
	 *            DOM element of the layer definition from which this definition
	 *            is being created (could be null)
	 * @param params
	 *            AVList passed to the {@link DelegatorTiledImageLayer} (could
	 *            be null)
	 * @return New delegate if the definition is valid for this delegate
	 */
	IDelegate fromDefinition(String definition, Element layerElement, AVList params);

	/**
	 * Generate a definition string for this delegate. Must be a string accepted
	 * by the {@code fromDefinition()} function.
	 * 
	 * @param layerElement
	 *            DOM element of the layer; can add elements to this element if
	 *            this delegate requires (could be null)
	 * @return
	 */
	String toDefinition(Element layerElement);
}
